# Generated by Django 4.2.1 on 2023-06-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='merchant.CartItem', to='merchant.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.shop'),
        ),
    ]
